version: '3.8'

services:
  postgres_primary:
    image: postgres:14
    container_name: postgres_primary
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_REPLICATION_USER: replicator
      POSTGRES_REPLICATION_PASSWORD: replicator_password
    volumes:
      - ./primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - postgres_primary_data:/var/lib/postgresql/data_primary
      - postgres_archive:/var/lib/postgresql/data_primary/archive
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  postgres_standby:
    image: postgres:14
    container_name: postgres_standby
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_REPLICATION_USER: replicator
      POSTGRES_REPLICATION_PASSWORD: replicator_password
      PRIMARY_HOST: postgres_primary
    volumes:
      - ./standby/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./standby/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - postgres_standby_data:/var/lib/postgresql/data_standby
    ports:
      - "5433:5432"
    depends_on:
      - postgres_primary
    command: >
      bash -c "
        until pg_isready --host=postgres_primary --port=5432; do sleep 1; done;
        pg_basebackup -h postgres_primary -D /var/lib/postgresql/data -U replicator -v -P --wal-method=stream;
        postgres -c config_file=/etc/postgresql/postgresql.conf
      "

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "5434:5432"
    depends_on:
      - postgres_primary
      - postgres_standby

  keycloak:
    build: ./keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: haproxy
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "2000:8080"
    depends_on:
      - haproxy
    command: start --optimized

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: dirigible/Dockerfile.frontend
  #   container_name: dirigible_frontend
  #   networks:
  #     - dirigible_network
  #   ports:
  #     - "8081:8080"  # Map host port 8081 to container port 8080
  #   environment:
  #     - SERVICE_NAME=service1  # Name of your service as registered in Keycloak

  # backend:
  #   build:
  #     context: .
  #     dockerfile: dirigible/Dockerfile.backend
  #   container_name: dirigible_backend
  #   networks:
  #     - dirigible_network
  #   ports:
  #     - "8082:8080"  # Map host port 8082 to container port 8080
  #   environment:
  #     - SERVICE_NAME=service2  # Name of your service as registered in Keycloak

  # fullstack:
  #   build:
  #     context: .
  #     dockerfile: dirigible/Dockerfile.fullstack
  #   container_name: dirigible_fullstack
  #   networks:
  #     - dirigible_network
  #   ports:
  #     - "8083:8080"  # Map host port 8083 to container port 8080
  #   environment:
  #     - SERVICE_NAME="tabler fullstack  # Name of your service as registered in Keycloak

volumes:
  postgres_primary_data:
  postgres_standby_data:
  postgres_archive:

networks:
  dirigible_network:
    driver: bridge
