FROM dirigiblelabs/dirigible:latest

COPY tabler/gen/ui target/dirigible/repository/root/registry/public/tabler/gen/ui
COPY tabler/gen/index.html target/dirigible/repository/root/registry/public/tabler/gen/index.html
